# Generated by Django 3.0.8 on 2020-07-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('title', 'link')},
        ),
    ]
