# Generated by Django 3.0.8 on 2020-11-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pages', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_books',
            },
        ),
    ]
