# Generated by Django 3.0.8 on 2020-11-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'polls_department',
            },
        ),
    ]
