# Generated by Django 3.0.8 on 2020-12-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
